name: "Run linters"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 17.2
        uses: actions/setup-node@v1
        with:
          node-version: 17.2

      - run: npm ci

      # ESLint
      - run: npm run lint:es

      # stylelint
      - run: npm run lint:style
